### ISSUE TITLE
xboxapi not Work?

### ISSUE THREAD

**Issue by marcuxyz** [xboxapi/Python-Wrapper#19]
Hello,
Is xboxapi.com not working?
I tried to test api via Curl but it does not return the data.

**Comment by ghost** [comment]
The API is working fine for me. You'll have to provide me with the output you're getting, otherwise I don't know what to look for.

When sending a curl request can you enable verbose and post the entire output here please? Make sure to strip your API key (`X-AUTH` headers) from the request and curl command.

**Comment by marcuxyz** [comment]
Hi @slash0pt ,
Thanks for awnser.

I was running:

`curl -s -H "X-AUTH: My API KEY" https://xboxapi.com/v2/xboxone-gold-lounge`

But an error occurs:

> {
>     "success": false,
>     "error_code": 401,
>     "error_message": "Looks like you just got hit with a security audit &#x1f61e;\nPlease go to <a href=\"https:\/\/account.live.com\/Activity\">https:\/\/account.live.com\/Activity<\/a> and authorise the server. Its IP is 162.243.154.64"
> }%

**Comment by djekl** [comment]
I have received an email from Marcus explaining that the error tells all.

Here is that email;

--------

Hey Marcus,

The error explains it all. Your request to login via XboxAPI has been stopped for security reasons.

If you visit https://account.live.com/Activity in your browser you will see a security request against the Server IP of "162.243.154.64". Simply click the "This is me" button, or something similar, and it will work for you then. Its usually because you don't live in the USA, and the server is hosted there, so technically you are logging into your Xbox account from the USA.

Regards,
Alan

--------

This is also now resolved
