### ISSUE TITLE
401 Unauthorized Responses

### ISSUE THREAD

**Issue by hogiyogi** [xboxapi/Python-Wrapper#25]
Hi,

I am new here and am really excited to see what I could do with this awesome api for xbox :D 

I am running into issues, however. For some reason, I am getting 401 Unauthorized errors at unexpected times. I am trying to use this request:

GET https://xboxapi.com/v2/2533274813099285/game-stats/950328474
and I have my X-Auth header with my api key.

For some reason, I can run this code fine in Postman and get a 200 response back. When I try to run this from my C# code it gives me a 401 Unauthorized. 

This xuid is my friend's so I don't know if that is the issue and I can't make the request without him having his own api key? In my head, it wouldn't make sense for everyone that uses the app to have to have a separate api key. Also, it wouldn't make sense because since it worked in Postman I know it is possible.

Any ideas on what I could be doing wrong?

I have tried regenerating my api key.
Also, sometimes the request won't work for my own xuid when it has a few minutes before. I am fairly confused as to what is going on.

Any help is appreciated.

Thanks,
hogiyogi597

**Comment by ghost** [comment]
> I am new here and am really excited to see what I could do with this awesome api for xbox :D

Awesome, glad to have you. 🤖 

> I am running into issues, however. For some reason, I am getting 401 Unauthorized errors at unexpected times.

Can you post the response body and headers you're getting from the endpoint? 401 status code should yield a JSON response with detailed information on why the request failed.

It is possible that you're running into the rate limit for making calls to the API under the free account. In the response headers you should see a few different values pertaining to rate limiting (see table below). Can you make sure you're not exceeding the limit when 401 is returned?

Header Key | Header Value  | Description
------------   | -------------- | -----------
| X-RateLimit-Limit |   120 | Total calls limit
| X-RateLimit-Remaining | 109 | Remaining calls
| X-RateLimit-Reset | 814 | TTL until `X-RateLimit-Remaining` is reset to `X-RateLimit-Limit` value


> For some reason, I can run this code fine in Postman and get a 200 response back. When I try to run this from my C# code it gives me a 401 Unauthorized.

Is this always failing in C# or only sometimes? Can you share the code that generates the request or even the raw request you're sending from C# (without your API key)?

**side-note**
This repo is a client library to access the Xbox API. I'm not the main developer for the Xbox API, only this repo, so normally these type of issues are posted over at: https://github.com/xboxapi/Xbox-One-API-Issues/issues. We can continue this issue here this time though, but future issues (if not related to this library) shouldn't be posted here.
 
☠️

**Comment by hogiyogi** [comment]
My apologies for the incorrect post placement. I appreciate your timely response despite that.

No, there would be no way I am exceeding the limit. I am on the free tier which supplies me 120 requests per hour, correct? I think the max I have used would be 15 an hour or so. I am still in the very early stages of development / proof of concept.

Here is the thing, when I query for game-stats for my own xuid, the request works great and I get everything I want. If I query for the game-stats with my friend's xuid, I get the 401 unauthorized response. To eliminate outlying variables while testing, I re logged in on XboxApi.com and generated a new api key. I tried my own xuid and it worked in both Postman and my code but my friend's xuid will only work in Postman.

Here is the request I am making. I may be making just a dumb mistake or maybe I am approaching the problem incorrectly. Any suggestions are appreciated.

```
client.DefaultRequestHeaders.Add("X-Auth", apiKey);
client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
string responseString = "";
try
{
     responseString = await client.GetStringAsync($"{baseURL}/{xuid}/game-stats/{gameID}");
}
catch(HttpRequestException e)
{
     string errorMessage = "[ERROR] Unable to process request! \nReason: " + e.Message;
     Console.Out.WriteLine(errorMessage);
     return errorMessage;
}
```

**Comment by djekl** [comment]
@voidpirate Thanks for dealing with this!  Going above and beyond haha 👍 

@hogiyogi597 You sent me an email regarding this, and I have replied explaining that the 401 request is auth. I have also suggested for you to try making a request against `/v2/profile` to ensure its not the XUID thats to blame, always test against an endpoint that takes no options (this ensures that your requesting your own profile, and won't run into any privacy issues).

If you were to hit the API limit, you would get a `403 - Forbiden` response error.

**Comment by ghost** [comment]
> If you were to hit the API limit, you would get a 403 - Forbiden response error.

oh yeah, derp :)

**Comment by hogiyogi** [comment]
Ok so I think I have figured out the majority of the issues. My last question, is there an endpoint for me to refresh my api key once it has expired? 

Also, I just wanted to thank you both for the prompt responses and for trying to help me through these issues. :D

**Comment by djekl** [comment]
@hogiyogi597 No, if you choose not to save the password with us, or choose to use the oAuth login, then you will need to visit your XboxAPI profile, and re-link the accounts
